name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Fix Project Structure
        run: |
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/java/com/rabie/tv
          mv *.xml app/src/main/res/layout/ 2>/dev/null || true
          mv AndroidManifest.xml app/src/main/ 2>/dev/null || true
          mv *.java app/src/main/java/com/rabie/tv/ 2>/dev/null || true
      - name: Grant Permission
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Rabie-TV-Pro-APK
          path: "**/*.apk"
